Continuous-Deployment:
  needs: build-and-push-ecr-image
  runs-on: self-hosted
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Stop and remove existing container
      run: |
        if [ $(docker ps -aq -f name=loan_default) ]; then
          docker stop loan_default
          docker rm -fv loan_default
        else
          echo "No existing container"
        fi

    - name: Pull latest image
      run: |
        docker pull ${{ needs.build-and-push-ecr-image.outputs.image }}

    - name: Run Docker Image
      run: |
        docker run -d -p 8080:8080 --name=loan_default \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_REGION=${{ secrets.AWS_REGION }} \
          ${{ needs.build-and-push-ecr-image.outputs.image }}

    - name: Clean previous images and containers
      run: docker system prune -f
